'use strict';
const $=id=>document.getElementById(id),make=(tag,text,cls)=>{const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n;};
let page=1,pages=1,controller,detailController,timer,paused=false;
const reduced=matchMedia('(prefers-reduced-motion:reduce)');
function motion(){const stop=paused||document.hidden||reduced.matches;document.body.classList.toggle('timeline-paused',stop);if(stop)document.querySelectorAll('.timeline-node').forEach(node=>node.getAnimations().forEach(animation=>animation.cancel()));$('pauseMotion').textContent=paused?'Reprendre l’animation':'Pause animation';$('pauseMotion').setAttribute('aria-pressed',String(paused));}
$('pauseMotion').onclick=()=>{paused=!paused;motion();};document.addEventListener('visibilitychange',motion);reduced.addEventListener('change',motion);motion();
const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){observer.unobserve(entry.target);if(!paused&&!reduced.matches&&!document.hidden)entry.target.animate([{opacity:0,transform:'translateY(18px)'},{opacity:1,transform:'translateY(0)'}],{duration:550,easing:'ease-out'});}},{threshold:.08});
async function api(path,signal){const response=await fetch(path,{cache:'no-store',signal});const data=await response.json();if(!response.ok)throw Error(data.error||'La chronologie est indisponible.');return data;}
async function openEvent(row){detailController?.abort();detailController=new AbortController();$('eventTitle').textContent=row.title;$('eventDate').textContent=Timeline.date(row);$('eventText').textContent='Chargement…';$('eventDialog').showModal();try{const data=await api('/api/timeline/'+row.id,detailController.signal);$('eventText').textContent=data.description||'Aucun récit complémentaire pour le moment.';}catch(error){if(error.name!=='AbortError')$('eventText').textContent=error.message;}}
async function load(){
 clearTimeout(timer);controller?.abort();const current=controller=new AbortController();$('timelineNotice').textContent='';$('timelineList').setAttribute('aria-busy','true');
 try{const data=await api('/api/timeline?'+new URLSearchParams({page,q:$('timelineSearch').value,kind:$('timelineKind').value}),current.signal);page=data.page;pages=data.pages;observer.disconnect();$('timelineList').replaceChildren();
 for(const row of data.items){const event=make('article','','timeline-node '+row.kind),card=make('div','','timeline-card');card.append(make('div',row.kind==='era'?'ÈRE DU MONDE':'ÉVÉNEMENT','kicker'),make('h2',row.title));if(row.description)card.append(make('p',row.description+(row.description.length===240?'…':'')));const button=make('button','Découvrir le récit ↗');button.setAttribute('aria-label','Lire : '+row.title);button.onclick=()=>openEvent(row);card.append(button);const point=make('span','','timeline-point');point.setAttribute('aria-hidden','true');event.append(make('div',Timeline.date(row),'timeline-date'),point,card);$('timelineList').append(event);observer.observe(event);}
 $('timelineEmpty').hidden=data.total!==0;$('timelineEmpty').textContent=$('timelineSearch').value||$('timelineKind').value!=='all'?'Aucun événement ne correspond à ces filtres.':'Les premiers événements de la chronologie attendent encore d’être révélés.';$('timelineCount').textContent=data.total+' repère'+(data.total>1?'s':'')+' dans la mémoire du monde';$('timelinePager').hidden=pages<=1;$('prevPage').disabled=page<=1;$('nextPage').disabled=page>=pages;$('pageInfo').textContent=page+' / '+pages;
 }catch(error){if(error.name!=='AbortError'){$('timelineNotice').textContent=error.message;$('timelineList').replaceChildren();$('timelinePager').hidden=true;}}
 finally{if(controller===current)$('timelineList').setAttribute('aria-busy','false');}
}
$('timelineSearch').oninput=()=>{page=1;clearTimeout(timer);controller?.abort();timer=setTimeout(load,250);};$('timelineKind').onchange=()=>{page=1;load();};$('prevPage').onclick=()=>{page--;load();};$('nextPage').onclick=()=>{page++;load();};$('retryTimeline').onclick=load;
$('closeEvent').onclick=()=>$('eventDialog').close();$('eventDialog').addEventListener('close',()=>detailController?.abort());
const toggle=document.querySelector('.menu-toggle'),nav=$('mainNav');function closeMenu(){nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Ouvrir le menu');}
toggle.onclick=()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Fermer le menu':'Ouvrir le menu');};document.addEventListener('click',e=>{if(!e.target.closest('.topbar'))closeMenu();});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});document.querySelector('.topbar').addEventListener('focusout',e=>{if(!e.currentTarget.contains(e.relatedTarget))closeMenu();});matchMedia('(max-width:1080px)').addEventListener('change',closeMenu);
new ResizeObserver(()=>document.documentElement.style.setProperty('--header-size',document.querySelector('.topbar').getBoundingClientRect().height+'px')).observe(document.querySelector('.topbar'));
(async()=>{try{const {user}=await api('/api/session');const allowed=user&&['player','mj'].includes(user.role);document.body.classList.toggle('access-locked',!allowed);document.querySelector('.account-link').textContent=user?'Mon compte':'Connexion';$('chronologyContent').hidden=!allowed;$('chronologyHero').hidden=!allowed;$('accessGate').hidden=!!allowed;$('editTimeline').hidden=user?.role!=='mj';if(allowed)await load();}catch(error){$('timelineNotice').textContent=error.message;$('accessGate').hidden=false;}})();
