(function(root){
 'use strict';
 const size={width:2400,height:1800};
 function parents(tree,id){return tree.edges.filter(e=>e.to===id).map(e=>e.from);}
 function canUnlock(tree,id,learned){const node=tree.nodes.find(n=>n.id===id);if(!node)return false;const required=parents(tree,id);return !required.length||(node.requirement_mode==='any'?required.some(p=>learned.has(p)):required.every(p=>learned.has(p)));}
 function prune(tree,learned){const next=new Set([...learned].filter(id=>tree.nodes.some(n=>n.id===id)));let changed=true;while(changed){changed=false;for(const id of next)if(!canUnlock(tree,id,next)){next.delete(id);changed=true;}}return next;}
 function cyclic(tree,from,to){if(from===to)return true;const todo=[to],seen=new Set();while(todo.length){const id=todo.pop();if(id===from)return true;if(seen.has(id))continue;seen.add(id);todo.push(...tree.edges.filter(e=>e.from===id).map(e=>e.to));}return false;}
 class Board {
  constructor(host,options={}){
   this.host=host;this.options=options;this.zoom=1;this.pan={x:0,y:0};this.selected=null;this.learned=null;this.linkMode=false;this.linkSource=null;this.tree={nodes:[],edges:[]};this.buttons=new Map();this.frame=null;
   host.classList.add('skill-board');this.world=document.createElement('div');this.world.className='skill-world';this.svg=document.createElementNS('http://www.w3.org/2000/svg','svg');this.svg.setAttribute('viewBox','0 0 2400 1800');this.svg.classList.add('skill-lines');this.svg.setAttribute('aria-hidden','true');this.nodes=document.createElement('div');this.nodes.className='skill-nodes';this.world.append(this.svg,this.nodes);host.append(this.world);
   host.addEventListener('pointerdown',e=>this.down(e));host.addEventListener('pointermove',e=>this.move(e));host.addEventListener('pointerup',e=>this.up(e));host.addEventListener('pointercancel',()=>this.cancel());
   host.addEventListener('wheel',e=>{if(e.ctrlKey){e.preventDefault();this.zoomBy(e.deltaY<0?1.12:1/1.12);}},{passive:false});
   this.resize=new ResizeObserver(()=>{const w=host.clientWidth,h=host.clientHeight;if(w&&h&&(w!==this.lastWidth||h!==this.lastHeight)){this.lastWidth=w;this.lastHeight=h;this.fit();}});this.resize.observe(host);
  }
  transform(){this.world.style.transform=`translate(${this.pan.x}px,${this.pan.y}px) scale(${this.zoom})`;this.options.onZoom?.(this.zoom);}
  fit(){const nodes=this.tree.nodes;if(!this.host.clientWidth)return;const minX=nodes.length?Math.min(...nodes.map(n=>n.x))-115:900,maxX=nodes.length?Math.max(...nodes.map(n=>n.x))+115:1500,minY=nodes.length?Math.min(...nodes.map(n=>n.y))-85:600,maxY=nodes.length?Math.max(...nodes.map(n=>n.y))+105:1200;this.zoom=Math.min(1.1,Math.max(.2,Math.min(this.host.clientWidth/(maxX-minX+80),this.host.clientHeight/(maxY-minY+80))));this.pan={x:this.host.clientWidth/2-(minX+maxX)/2*this.zoom,y:this.host.clientHeight/2-(minY+maxY)/2*this.zoom};this.transform();}
  zoomBy(factor){const next=Math.max(.2,Math.min(2,this.zoom*factor)),cx=this.host.clientWidth/2,cy=this.host.clientHeight/2;this.pan={x:cx-(cx-this.pan.x)*next/this.zoom,y:cy-(cy-this.pan.y)*next/this.zoom};this.zoom=next;this.transform();}
  render(tree){this.cancel();this.tree=tree;this.nodes.replaceChildren();this.buttons.clear();this.host.style.setProperty('--affinity',tree.color||'#c6a66a');this.host.style.backgroundImage=tree.image?`linear-gradient(#091011b8,#091011e8),url("${tree.image}")`:'';
   for(const node of tree.nodes){const button=document.createElement('button');button.type='button';button.className='skill-node '+node.kind;button.dataset.id=node.id;button.setAttribute('aria-label',node.name);const face=document.createElement('span');face.className='skill-face';if(node.image){const img=document.createElement('img');img.src=node.image;img.alt='';img.draggable=false;img.decoding='async';face.append(img);}else face.textContent=node.symbol||'✦';const name=document.createElement('span');name.className='skill-node-name';name.textContent=node.name;button.append(face,name);button.style.transform=`translate(${node.x-32}px,${node.y-32}px)`;
    button.addEventListener('click',e=>{if(this.suppressClick){this.suppressClick=false;return;}this.pick(node.id);});
    button.addEventListener('keydown',e=>{if(this.options.editable&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();this.options.onMoveStart?.();node.x=Math.max(60,Math.min(2340,node.x+({ArrowLeft:-24,ArrowRight:24}[e.key]||0)));node.y=Math.max(60,Math.min(1740,node.y+({ArrowUp:-24,ArrowDown:24}[e.key]||0)));this.position(node);this.options.onMove?.(node);}});
    this.nodes.append(button);this.buttons.set(node.id,button);
   }this.drawEdges();this.states();this.transform();
  }
  path(edge){const a=this.tree.nodes.find(n=>n.id===edge.from),b=this.tree.nodes.find(n=>n.id===edge.to);if(!a||!b)return '';return `M ${a.x} ${a.y+32} C ${a.x} ${a.y+90}, ${b.x} ${b.y-90}, ${b.x} ${b.y-37}`;}
  drawEdges(){this.svg.replaceChildren();this.paths=[];const ns='http://www.w3.org/2000/svg',defs=document.createElementNS(ns,'defs'),marker=document.createElementNS(ns,'marker');marker.id='tree-arrow';marker.setAttribute('viewBox','0 0 10 10');marker.setAttribute('refX','9');marker.setAttribute('refY','5');marker.setAttribute('markerWidth','5');marker.setAttribute('markerHeight','5');marker.setAttribute('orient','auto');const arrow=document.createElementNS(ns,'path');arrow.setAttribute('d','M 0 0 L 10 5 L 0 10 z');arrow.setAttribute('fill','#b79b65');marker.append(arrow);defs.append(marker);this.svg.append(defs);
   for(const edge of this.tree.edges){const path=document.createElementNS(ns,'path');path.setAttribute('d',this.path(edge));path.setAttribute('marker-end','url(#tree-arrow)');this.svg.append(path);this.paths.push({edge,path});}
  }
  states(){for(const node of this.tree.nodes){const button=this.buttons.get(node.id);button.classList.toggle('selected',node.id===this.selected);button.classList.toggle('link-source',node.id===this.linkSource);button.setAttribute('aria-pressed',String(node.id===this.selected));button.classList.toggle('learned',!!this.learned?.has(node.id));button.classList.toggle('locked',!!this.learned&&!canUnlock(this.tree,node.id,this.learned));}for(const {edge,path} of this.paths||[]){path.classList.toggle('highlighted',edge.to===this.selected||edge.from===this.selected);path.classList.toggle('learned',!!this.learned?.has(edge.from)&&!!this.learned?.has(edge.to));}}
  pick(id){if(this.linkMode){if(!this.linkSource){this.linkSource=id;this.states();this.options.onLinkStart?.(id);}else{const from=this.linkSource;this.linkSource=null;this.states();if(cyclic(this.tree,from,id))this.options.onError?.('Ce lien crée une boucle de prérequis.');else if(this.tree.edges.some(e=>e.from===from&&e.to===id))this.options.onError?.('Ces compétences sont déjà reliées.');else this.options.onConnect?.(from,id);}return;}this.selected=id;this.states();this.options.onSelect?.(id);}
  setLinkMode(value){this.linkMode=value;this.linkSource=null;this.host.classList.toggle('linking',value);this.states();}
  position(node){this.buttons.get(node.id).style.transform=`translate(${node.x-32}px,${node.y-32}px)`;for(const {edge,path} of this.paths)if(edge.from===node.id||edge.to===node.id)path.setAttribute('d',this.path(edge));}
  down(e){if(e.button!==0||e.isPrimary===false)return;const target=e.target.closest('.skill-node');if(target&&(!this.options.editable||this.linkMode))return;const node=target?this.tree.nodes.find(n=>n.id===target.dataset.id):null;if(node)this.options.onMoveStart?.();this.drag={id:e.pointerId,startX:e.clientX,startY:e.clientY,node,x:node?node.x:this.pan.x,y:node?node.y:this.pan.y,moved:false};this.host.setPointerCapture(e.pointerId);}
  move(e){const d=this.drag;if(!d||d.id!==e.pointerId)return;const dx=e.clientX-d.startX,dy=e.clientY-d.startY;if(Math.abs(dx)+Math.abs(dy)<5&&!d.moved)return;d.moved=true;this.suppressClick=true;d.dx=dx;d.dy=dy;if(this.frame)return;this.frame=requestAnimationFrame(()=>{this.frame=null;this.applyDrag();});}
  applyDrag(){const d=this.drag;if(!d||!d.moved)return;if(d.node){d.node.x=Math.round(Math.max(60,Math.min(2340,d.x+d.dx/this.zoom)));d.node.y=Math.round(Math.max(60,Math.min(1740,d.y+d.dy/this.zoom)));this.position(d.node);}else{this.pan={x:d.x+d.dx,y:d.y+d.dy};this.transform();}}
  up(e){if(!this.drag||this.drag.id!==e.pointerId)return;this.applyDrag();const d=this.drag;this.drag=null;if(this.frame){cancelAnimationFrame(this.frame);this.frame=null;}if(d.moved&&d.node)this.options.onMove?.(d.node);if(this.host.hasPointerCapture(e.pointerId))this.host.releasePointerCapture(e.pointerId);if(!d.moved&&d.node)this.pick(d.node.id);setTimeout(()=>{this.suppressClick=false;},0);}
  cancel(){if(this.frame)cancelAnimationFrame(this.frame);this.frame=null;if(this.drag?.node){this.drag.node.x=this.drag.x;this.drag.node.y=this.drag.y;this.position(this.drag.node);}this.drag=null;}
 }
 const api={Board,parents,canUnlock,prune,cyclic,size};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.SkillGraph=api;
})(globalThis);
