'use strict';
const $=id=>document.getElementById(id),make=(tag,text,cls)=>{const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n;};
let tree=null,selected=null,learned=new Set(),page=1,pages=1,controller,affinityId=null,sequence=0,listSequence=0;
const names={active:'Active',passive:'Passive',ultimate:'Ultime'};
const board=new SkillGraph.Board($('treeBoard'),{onSelect:id=>openCard(id,true),onZoom:z=>$('zoomValue').textContent=Math.round(z*100)+' %'});
async function api(path,signal){const response=await fetch(path,{cache:'no-store',signal});const data=await response.json();if(!response.ok)throw Error(data.error||'Les Affinités sont indisponibles.');return data;}
let cardTimer,pinned=false,cardPointer=null,cardFrame=null;
const card=$('skillInspector');
function closeCard(){clearTimeout(cardTimer);if(cardFrame)cancelAnimationFrame(cardFrame);cardFrame=null;cardPointer=null;card.hidden=true;pinned=false;selected=null;board.selected=null;board.states();}
function positionCard(){const anchor=board.buttons.get(selected);if(!anchor)return;const rect=anchor.getBoundingClientRect(),top=document.querySelector('.topbar').getBoundingClientRect().bottom+10;const w=card.offsetWidth,h=card.offsetHeight;const cursor=!pinned&&cardPointer;let x=cursor?cursor.x+rect.width+18:rect.right+18;if(x+w>innerWidth-12)x=cursor?cursor.x-w-rect.width-18:rect.left-w-18;card.style.left=Math.max(12,Math.min(x,innerWidth-w-12))+'px';card.style.top=Math.max(top,Math.min(cursor?cursor.y+18:rect.top-20,innerHeight-h-12))+'px';}
function openCard(id,pin=false){clearTimeout(cardTimer);if(pinned&&!pin)return;selected=id;pinned=pin;board.selected=id;board.states();showSkill();card.hidden=false;positionCard();}
function scheduleClose(){clearTimeout(cardTimer);if(!pinned)cardTimer=setTimeout(()=>{if(!card.matches(':hover')&&!card.contains(document.activeElement))closeCard();},180);}
$('treeBoard').addEventListener('pointerover',e=>{const node=e.target.closest('.skill-node');if(node&&e.pointerType!=='touch'&&innerWidth>=700){cardPointer={x:e.clientX,y:e.clientY};openCard(node.dataset.id);}});
$('treeBoard').addEventListener('pointermove',e=>{if(pinned||card.hidden||e.pointerType==='touch'||!e.target.closest('.skill-node'))return;cardPointer={x:e.clientX,y:e.clientY};if(!cardFrame)cardFrame=requestAnimationFrame(()=>{cardFrame=null;if(!card.hidden)positionCard();});});
$('treeBoard').addEventListener('pointerout',e=>{if(e.target.closest('.skill-node')&&!e.relatedTarget?.closest?.('.skill-node'))scheduleClose();});
$('treeBoard').addEventListener('focusin',e=>{const node=e.target.closest('.skill-node');if(node&&node.matches(':focus-visible')){cardPointer=null;openCard(node.dataset.id);}});
$('treeBoard').addEventListener('focusout',scheduleClose);
$('treeBoard').addEventListener('pointerdown',e=>{if(!e.target.closest('.skill-node'))closeCard();});
$('treeBoard').addEventListener('wheel',closeCard,{passive:true});
card.addEventListener('pointerenter',()=>clearTimeout(cardTimer));card.addEventListener('pointerleave',scheduleClose);card.addEventListener('focusout',scheduleClose);
$('closeSkill').onclick=()=>{const node=board.buttons.get(selected);closeCard();node?.focus({preventScroll:true});closeCard();};
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeCard();});
document.addEventListener('pointerdown',e=>{if(!card.contains(e.target)&&!e.target.closest('.skill-node'))closeCard();});
window.addEventListener('resize',closeCard);
function updateSimulation(){learned=SkillGraph.prune(tree,learned);board.learned=$('simulate').checked?learned:null;board.states();const points=tree.nodes.filter(n=>learned.has(n.id)).reduce((sum,n)=>sum+n.points,0);$('simulationTotal').textContent=$('simulate').checked?learned.size+' compétences · '+points+' points simulés':'Consultation de l’arbre';}
function showSkill(){
 const node=tree?.nodes.find(n=>n.id===selected);$('skillDetail').hidden=!node;if(!node)return;
 $('skillName').textContent=node.name;$('skillType').textContent=names[node.kind]+' · '+node.points+' point'+(node.points>1?'s':'')+' de déblocage';
 for(const [key,id,fallback] of [['description','skillDescription','Aucune description renseignée.'],['acquisition','skillAcquisition','Consultez les prérequis ci-dessous.'],['usage','skillUsage','Utilisation à préciser par le MJ.'],['cost','skillCost','Coût à préciser par le MJ.'],['cooldown','skillCooldown','Non précisé.'],['range','skillRange','Non précisée.']])$(id).textContent=node[key]||fallback;
 const required=SkillGraph.parents(tree,node.id);$('skillPrerequisites').replaceChildren();$('requirementMode').textContent=required.length?(node.requirement_mode==='any'?'Au moins un de ces prérequis :':'Tous ces prérequis :'):'Aucun prérequis dans cet arbre.';
 for(const id of required){const item=make('li',''),button=make('button',(learned.has(id)&&$('simulate').checked?'✓ ':'')+tree.nodes.find(n=>n.id===id).name);button.onclick=()=>{selected=id;board.selected=id;board.states();openCard(id,true);};item.append(button);$('skillPrerequisites').append(item);}
 $('learnSkill').hidden=!$('simulate').checked;$('learnSkill').disabled=!learned.has(node.id)&&!SkillGraph.canUnlock(tree,node.id,learned);$('learnSkill').textContent=learned.has(node.id)?'Retirer du parcours':SkillGraph.canUnlock(tree,node.id,learned)?'Ajouter au parcours':'Prérequis manquants';
}
let affinity=null,bookItems=[],bookIndex=0,bookTotal=0;
function stage(name){closeCard();$('grimoire').hidden=name!=='book';$('specializationStage').hidden=name!=='paths';$('talentLayout').hidden=name!=='tree';$('treeNavigation').hidden=name!=='tree';$('treeOptions').hidden=name!=='tree';$('treeOptions').open=false;}
function showBook(){stage('book');$('chooseAffinity').disabled=!affinity;if(!affinity)return;$('bookName').textContent=affinity.name;$('bookDescription').textContent=affinity.lore||affinity.description||'Les secrets de cette Affinité attendent encore leur inscription dans le grimoire.';$('bookSymbol').textContent=affinity.symbol||'✦';const cover=affinity.cover||affinity.image;$('bookArt').style.backgroundImage=cover?`linear-gradient(0deg,#0b1019bb,transparent),url("${cover}")`:'';$('bookPage').style.setProperty('--affinity',affinity.color);$('bookFolio').textContent=String((page-1)*20+bookIndex+1).padStart(2,'0');if(!matchMedia('(prefers-reduced-motion: reduce)').matches)$('bookPage').animate([{opacity:.3,transform:'rotateY(-5deg)'},{opacity:1,transform:'rotateY(0)'}],{duration:320,easing:'ease-out'});}
function showPaths(){if(!affinity)return;stage('paths');$('specializationTitle').textContent=affinity.name;$('specializationCards').replaceChildren();[affinity,...affinity.paths].forEach((path,index)=>{const panel=make('article','','specialization-card');panel.style.setProperty('--affinity',path.color||affinity.color);const art=make('div','','specialization-art');if(path.image){const img=document.createElement('img');img.src=path.image;img.alt='';art.append(img);}else art.append(make('span',path.symbol||'✦','specialization-sigil'));panel.append(art,make('p',['I','II','III'][index],'specialization-number'),make('h2',path.path_name),make('p',path.role||'Rôle à découvrir','specialization-role'),make('p',path.description||'Cette voie attend d’être décrite par le MJ.','specialization-description'));const preview=make('div','','specialization-preview');for(const node of path.nodes.slice(0,3)){const icon=make('span',node.image?'':node.symbol||'✦',node.kind);icon.title=node.name;if(node.image){const img=document.createElement('img');img.src=node.image;img.alt=node.name;icon.append(img);}preview.append(icon);}panel.append(preview);const button=make('button',path.nodes.length?'Explorer cet arbre →':'Arbre à venir','specialization-action');button.disabled=!path.nodes.length;button.onclick=()=>openPath(index);panel.append(button);$('specializationCards').append(panel);});}
function openPath(index){tree=index?affinity.paths[index-1]:affinity;selected=null;learned=new Set();board.selected=null;stage('tree');$('treeName').textContent=affinity.name+' · '+tree.path_name;$('treeEmpty').hidden=!!tree.nodes.length;board.render(tree);board.fit();updateSimulation();}
async function openAffinity(id){closeCard();controller?.abort();const request=controller=new AbortController(),seq=++sequence;affinityId=id;affinity=null;$('chooseAffinity').disabled=true;$('skillsNotice').textContent='Ouverture du grimoire…';try{const data=await api('/api/affinities/'+id,request.signal);if(seq!==sequence)return;affinity=SkillGraph.prepareAffinity(data.tree);$('skillsNotice').textContent='';showBook();}catch(error){if(error.name!=='AbortError')$('skillsNotice').textContent=error.message;}}
function bookControls(){const current=(page-1)*20+bookIndex+1;$('prevAffinity').disabled=current<=1;$('nextAffinity').disabled=current>=bookTotal;$('affinityPage').textContent=bookTotal?current+' / '+bookTotal:'Aucune Affinité publiée';}
async function loadAffinities(last=false){const seq=++listSequence;$('prevAffinity').disabled=true;$('nextAffinity').disabled=true;try{const data=await api('/api/affinities?page='+page);if(seq!==listSequence)return;page=data.page;pages=data.pages;bookItems=data.items;bookTotal=data.total;bookIndex=last?bookItems.length-1:0;$('affinityEmpty').hidden=!!bookTotal;$('bookPage').hidden=!bookTotal;bookControls();if(bookItems.length)await openAffinity(bookItems[bookIndex].id);else stage('book');}catch(error){$('skillsNotice').textContent=error.message;}}
function turnPage(delta){const next=bookIndex+delta;if(next>=0&&next<bookItems.length){bookIndex=next;bookControls();openAffinity(bookItems[bookIndex].id);}else if(delta<0&&page>1){page--;loadAffinities(true);}else if(delta>0&&page<pages){page++;loadAffinities();}}
$('chooseAffinity').onclick=showPaths;$('backPaths').onclick=showPaths;$('backBook').onclick=showBook;$('returnGrimoire').onclick=showBook;
$('learnSkill').onclick=()=>{if(!selected)return;if(learned.has(selected))learned.delete(selected);else if(SkillGraph.canUnlock(tree,selected,learned))learned.add(selected);updateSimulation();showSkill();};
$('simulate').onchange=()=>{if(tree){updateSimulation();showSkill();}};$('resetBuild').onclick=()=>{learned.clear();if(tree){updateSimulation();showSkill();}};
$('zoomIn').onclick=()=>board.zoomBy(1.2);$('zoomOut').onclick=()=>board.zoomBy(1/1.2);$('fitTree').onclick=()=>board.fit();
$('prevAffinity').onclick=()=>turnPage(-1);$('nextAffinity').onclick=()=>turnPage(1);
const toggle=document.querySelector('.menu-toggle'),nav=$('mainNav');function closeMenu(){nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');toggle.setAttribute('aria-label','Ouvrir le menu');}toggle.onclick=()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',String(open));toggle.setAttribute('aria-label',open?'Fermer le menu':'Ouvrir le menu');};document.addEventListener('click',e=>{if(!e.target.closest('.topbar'))closeMenu();});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu();});document.querySelector('.topbar').addEventListener('focusout',e=>{if(!e.currentTarget.contains(e.relatedTarget))closeMenu();});matchMedia('(max-width:1080px)').addEventListener('change',closeMenu);
new ResizeObserver(()=>document.documentElement.style.setProperty('--header-size',document.querySelector('.topbar').getBoundingClientRect().height+'px')).observe(document.querySelector('.topbar'));
(async()=>{try{const {user}=await api('/api/session');const allowed=user&&['mj','player'].includes(user.role);document.body.classList.toggle('access-locked',!allowed);$('skillsContent').hidden=!allowed;$('accessGate').hidden=!!allowed;$('editSkills').hidden=user?.role!=='mj';document.querySelector('.account-link').textContent=user?'Mon compte':'Connexion';if(allowed)await loadAffinities();}catch(error){$('skillsNotice').textContent=error.message;$('accessGate').hidden=false;}})();
