'use strict';
const $=id=>document.getElementById(id),meta=$('affinityForm'),skillForm=$('skillForm');
let csrf='',current=null,tree=null,selected=null,dirty=false,busy=false,page=1,pages=1,undo=[],redo=[],dragBefore=null;
const blank=()=>({name:'Nouvelle Affinité',description:'',color:'#c6a66a',symbol:'✦',image:null,nodes:[],edges:[]});
const board=new SkillGraph.Board($('treeBoard'),{editable:true,onSelect:id=>{selected=id;editSkill();},onMoveStart:()=>{dragBefore=JSON.stringify(tree);},onMove:node=>{record(dragBefore);selected=node.id;board.selected=selected;board.states();changed();editSkill();},onConnect:connect,onError:message=>notice(message),onLinkStart:()=>notice('Choisissez maintenant la compétence qui nécessite ce prérequis.'),onZoom:z=>$('zoomValue').textContent=Math.round(z*100)+' %'});
function notice(message){$('notice').textContent=message;}
const canLeave=()=>!dirty||confirm('Quitter cet arbre sans enregistrer le brouillon ?');
async function api(path,method='GET',data){const options={method,cache:'no-store',headers:{'X-CSRF-Token':csrf}};if(data instanceof FormData)options.body=data;else if(data!==undefined){options.headers['Content-Type']='application/json';options.body=JSON.stringify(data);}const response=await fetch(path,options);const result=await response.json();if(!response.ok)throw Error(result.error||'Le serveur est indisponible.');return result;}
async function run(task){if(busy)return;busy=true;$('workspace').inert=true;try{await task();}catch(error){notice(error.message);}finally{busy=false;$('workspace').inert=false;}}
function record(snapshot){if(!tree)return;undo.push(snapshot||JSON.stringify(tree));if(undo.length>30)undo.shift();redo=[];}
function changed(){dirty=true;$('saveState').textContent='Brouillon non enregistré';$('undoTree').disabled=!undo.length;$('redoTree').disabled=!redo.length;}
function draw(){board.selected=selected;board.render(tree);$('treeName').textContent=tree.name;$('treeCount').textContent=tree.nodes.length+' compétences · '+tree.edges.length+' liens';}
function fillMeta(){for(const key of ['name','description','color','symbol'])meta.elements[key].value=tree[key];$('deleteAffinity').hidden=!current;$('hideTree').hidden=!current?.published;$('publicationState').textContent=current?.published?'Une version est publiée':'Affinité privée';$('undoTree').disabled=!undo.length;$('redoTree').disabled=!redo.length;}
function openRow(row){current=row;tree=structuredClone(row?row.draft:blank());selected=null;dirty=!row;undo=[];redo=[];$('editor').hidden=false;$('emptyEditor').hidden=true;fillMeta();draw();board.fit();editSkill();$('saveState').textContent=row?'Brouillon enregistré':'Nouvelle Affinité · non enregistrée';board.setLinkMode(false);$('linkSkills').setAttribute('aria-pressed','false');}
async function list(){const data=await api('/api/admin/affinities?page='+page);page=data.page;pages=data.pages;$('affinitySelect').replaceChildren(new Option('Choisir une Affinité…',''));for(const row of data.items)$('affinitySelect').add(new Option(row.name+(row.published?' · Publiée':' · Privée'),row.id));if(current&&!data.items.some(row=>row.id===current.id))$('affinitySelect').add(new Option(current.draft.name,current.id));$('affinitySelect').value=current?.id||'';$('prevAffinity').disabled=page<=1;$('nextAffinity').disabled=page>=pages;$('affinityPage').textContent=page+' / '+pages;return data;}
function editSkill(){const node=tree?.nodes.find(n=>n.id===selected);skillForm.hidden=!node;$('chooseSkill').hidden=!!node;if(!node)return;$('skillHeading').textContent=node.name;for(const key of ['name','kind','symbol','description','acquisition','usage','cost','cooldown','range','points','x','y','requirement_mode'])skillForm.elements[key].value=node[key];$('iconPreview').hidden=!node.image;if(node.image)$('iconPreview').src=node.image;else $('iconPreview').removeAttribute('src');renderPrerequisites();}
function renderPrerequisites(){const node=tree.nodes.find(n=>n.id===selected);if(!node)return;$('prerequisites').replaceChildren();const required=SkillGraph.parents(tree,selected);for(const id of required){const li=document.createElement('li');li.append(document.createTextNode(tree.nodes.find(n=>n.id===id).name+' '));const button=document.createElement('button');button.type='button';button.textContent='Retirer le lien';button.onclick=()=>{record();tree.edges=tree.edges.filter(e=>!(e.from===id&&e.to===selected));changed();draw();renderPrerequisites();};li.append(button);$('prerequisites').append(li);}$('prerequisiteSelect').replaceChildren(new Option('Choisir un prérequis…',''));for(const n of tree.nodes)if(n.id!==selected&&!required.includes(n.id)&&!SkillGraph.cyclic(tree,n.id,selected))$('prerequisiteSelect').add(new Option(n.name,n.id));}
function connect(from,to){if(tree.edges.length>=600){notice('Limite de 600 liens atteinte.');return;}if(!from||!to||from===to||SkillGraph.cyclic(tree,from,to)){notice('Ce lien crée une boucle de prérequis.');return;}if(tree.edges.some(e=>e.from===from&&e.to===to)){notice('Ce lien existe déjà.');return;}record();tree.edges.push({from,to});selected=to;changed();draw();editSkill();notice('Prérequis ajouté. Enregistrez le brouillon pour le conserver.');}
meta.addEventListener('input',event=>{const key=event.target.name;if(!['name','color','symbol','description'].includes(key))return;record();tree[key]=event.target.value;changed();if(key!=='description')draw();});meta.onsubmit=event=>event.preventDefault();skillForm.onsubmit=event=>event.preventDefault();
skillForm.addEventListener('input',event=>{const key=event.target.name,node=tree.nodes.find(n=>n.id===selected);if(!key||!node)return;const numeric=['x','y','points'].includes(key);if(numeric&&!event.target.checkValidity())return;record();node[key]=numeric?Number(event.target.value):event.target.value;changed();if(['name','symbol','kind','x','y'].includes(key)){draw();$('skillHeading').textContent=node.name;}});
$('newAffinity').onclick=()=>{if(canLeave()){openRow(null);$('affinitySelect').value='';}};
$('affinitySelect').onchange=()=>{const id=$('affinitySelect').value;if(!id){$('affinitySelect').value=current?.id||'';return;}if(!canLeave()){$('affinitySelect').value=current?.id||'';return;}run(async()=>openRow(await api('/api/admin/affinities/'+id)));};
$('reloadAffinity').onclick=()=>{if(canLeave())run(async()=>{if(current)openRow(await api('/api/admin/affinities/'+current.id));await list();});};
for(const [id,delta] of [['prevAffinity',-1],['nextAffinity',1]])$(id).onclick=()=>run(async()=>{page=Math.max(1,Math.min(pages,page+delta));await list();});
$('addSkill').onclick=()=>{if(tree.nodes.length>=200){notice('Limite de 200 compétences atteinte.');return;}record();let x=Math.round(Math.max(60,Math.min(2340,($('treeBoard').clientWidth/2-board.pan.x)/board.zoom))),y=Math.round(Math.max(60,Math.min(1740,($('treeBoard').clientHeight/2-board.pan.y)/board.zoom)));for(let i=0;i<200&&tree.nodes.some(n=>Math.abs(n.x-x)<80&&Math.abs(n.y-y)<100);i++){x=x<2150?x+140:120;y=x===120?Math.min(1700,y+150):y;}const id=crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);tree.nodes.push({id,name:'Compétence '+(tree.nodes.length+1),kind:'active',symbol:'✦',image:null,description:'',acquisition:'',usage:'',cost:'',cooldown:'',range:'',points:1,x,y,requirement_mode:'all'});selected=id;changed();draw();editSkill();};
$('deleteSkill').onclick=()=>{if(!confirm('Supprimer cette compétence et les liens qui lui sont rattachés ?'))return;record();tree.nodes=tree.nodes.filter(n=>n.id!==selected);tree.edges=tree.edges.filter(e=>e.from!==selected&&e.to!==selected);selected=null;changed();draw();editSkill();};
$('linkSkills').onclick=()=>{board.setLinkMode(!board.linkMode);$('linkSkills').setAttribute('aria-pressed',String(board.linkMode));notice(board.linkMode?'Cliquez d’abord le prérequis, puis la compétence qu’il débloque.':'Déplacement des compétences activé.');};$('addPrerequisite').onclick=()=>connect($('prerequisiteSelect').value,selected);
$('zoomIn').onclick=()=>board.zoomBy(1.2);$('zoomOut').onclick=()=>board.zoomBy(1/1.2);$('fitTree').onclick=()=>board.fit();
function restoreHistory(source,target){if(!source.length)return;target.push(JSON.stringify(tree));tree=JSON.parse(source.pop());if(!tree.nodes.some(n=>n.id===selected))selected=null;dirty=true;fillMeta();draw();editSkill();$('saveState').textContent='Brouillon non enregistré';}
$('undoTree').onclick=()=>restoreHistory(undo,redo);$('redoTree').onclick=()=>restoreHistory(redo,undo);
async function save(){if(!meta.reportValidity()||(!skillForm.hidden&&!skillForm.reportValidity()))throw Error('Vérifiez les champs de l’Affinité et de la compétence.');const row=await api('/api/admin/affinities'+(current?'/'+current.id:''),current?'PUT':'POST',current?{tree,revision:current.revision}:tree);current=row;tree=structuredClone(row.draft);dirty=false;undo=[];redo=[];fillMeta();draw();editSkill();$('saveState').textContent='Brouillon enregistré';await list();return row;}
$('saveTree').onclick=()=>run(async()=>{await save();notice('Brouillon enregistré. La version joueur reste inchangée jusqu’à publication.');});
$('publishTree').onclick=()=>{if(confirm('Publier cet arbre et toutes ses compétences pour les joueurs ?'))run(async()=>{const row=dirty||!current?await save():current;current=await api('/api/admin/affinities/'+row.id+'/publish','POST',{revision:row.revision});fillMeta();await list();notice('Arbre publié pour les joueurs.');});};
$('hideTree').onclick=()=>{if(current&&confirm('Retirer cette Affinité de la vue joueurs ? Le brouillon sera conservé.'))run(async()=>{current=await api('/api/admin/affinities/'+current.id+'/hide','POST',{revision:current.revision});fillMeta();await list();notice('Affinité retirée de la vue joueurs.');});};
async function upload(file,purpose){if(!file)return null;if(file.size>10*1024*1024)throw Error('L’image dépasse 10 Mo.');const data=new FormData();data.append('image',file);if(purpose)data.append('purpose',purpose);return (await api('/api/admin/images','POST',data)).image;}
$('backgroundFile').onchange=()=>run(async()=>{const image=await upload($('backgroundFile').files[0]);if(image){record();tree.image=image;changed();draw();}$('backgroundFile').value='';});
$('iconFile').onchange=()=>run(async()=>{const node=tree.nodes.find(n=>n.id===selected);if(!node)return;const image=await upload($('iconFile').files[0],'skill-icon');if(image){record();node.image=image;changed();draw();editSkill();}$('iconFile').value='';});
$('removeBackground').onclick=()=>{record();tree.image=null;changed();draw();};$('removeIcon').onclick=()=>{const node=tree.nodes.find(n=>n.id===selected);if(node){record();node.image=null;changed();draw();editSkill();}};
$('deleteAffinity').onclick=()=>{if(current){$('deleteTitle').textContent='Supprimer « '+current.draft.name+' » ?';$('confirmName').value='';$('deleteDialog').showModal();}};$('cancelDelete').onclick=()=>$('deleteDialog').close();$('confirmName').oninput=()=>$('confirmName').setCustomValidity('');
$('deleteForm').onsubmit=event=>{event.preventDefault();if($('confirmName').value!==current.draft.name){$('confirmName').setCustomValidity('Retapez exactement le nom de l’Affinité.');$('confirmName').reportValidity();return;}$('deleteDialog').close();run(async()=>{await api('/api/admin/affinities/'+current.id,'DELETE',{revision:current.revision,confirmName:$('confirmName').value});current=null;tree=null;dirty=false;$('editor').hidden=true;$('emptyEditor').hidden=false;await list();notice('Affinité supprimée.');});};
window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});
(async()=>{try{const session=await api('/api/admin/session');csrf=session.csrf;const data=await list();$('workspace').hidden=false;if(data.items.length){openRow(await api('/api/admin/affinities/'+data.items[0].id));$('affinitySelect').value=current.id;}notice('Vos arbres restent privés jusqu’à leur publication.');}catch(error){notice(error.message+' ');const link=document.createElement('a');link.href='/account/';link.textContent='Se connecter';$('notice').append(link);}})();
