'use strict';
const $=id=>document.getElementById(id),form=$('eventForm'),make=(tag,text)=>{const n=document.createElement(tag);n.textContent=text;return n;};
let csrf='',current=null,page=1,pages=1,nextPosition=1,dirty=false,busy=false,importData=null,controller,sequence=0,timer;
function notice(text){$('notice').textContent=text;}
const canLeave=()=>!dirty||confirm('Quitter sans enregistrer cet événement ?');
async function api(path,method='GET',data,signal){const response=await fetch(path,{method,cache:'no-store',signal,headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:data===undefined?undefined:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw Error(result.error||'Requête impossible.');return result;}
async function run(task){if(busy)return;busy=true;$('timelineWorkspace').inert=true;try{await task();}catch(error){notice(error.message);}finally{busy=false;$('timelineWorkspace').inert=false;}}
function edit(row){current=row;dirty=false;form.reset();form.hidden=false;$('welcome').hidden=true;$('editorTitle').textContent=row?.title||'Nouvel événement';for(const key of ['title','kind','position','description','date_label','start_year','end_year'])form.elements[key].value=row?.[key]??({title:'',description:'',date_label:'',start_year:'',end_year:'',kind:'event',position:nextPosition}[key]);form.elements.visible.checked=!!row?.visible;$('deleteEvent').hidden=!row;$('saveState').textContent=row?'Enregistré':'Privé par défaut';}
async function load(){
 clearTimeout(timer);controller?.abort();const request=controller=new AbortController(),seq=++sequence;
 try{const data=await api('/api/admin/timeline?'+new URLSearchParams({page,q:$('search').value,kind:$('kindFilter').value}),'GET',undefined,request.signal);if(seq!==sequence)return;page=data.page;pages=data.pages;nextPosition=data.nextPosition;$('listCount').textContent=data.total+' éléments';$('pageInfo').textContent=page+' / '+pages;$('prevPage').disabled=page<=1;$('nextPage').disabled=page>=pages;$('eventList').replaceChildren();
 for(const row of data.items){const card=make('div','');card.className='journal-editor-row';card.append(make('strong',row.title),make('small',Timeline.date(row)+' · '+(row.visible?'Révélé':'Privé')));const button=make('button','Modifier');button.type='button';button.onclick=()=>{if(canLeave())run(async()=>edit(await api('/api/admin/timeline/'+row.id)));};card.append(button);$('eventList').append(card);}
 if(!data.total)$('eventList').append(make('p','Aucun événement. Importez votre frise ou créez le premier repère.'));
 }catch(error){if(error.name!=='AbortError')throw error;}
}
$('newEvent').onclick=()=>{if(canLeave())edit(null);};form.oninput=()=>{dirty=true;$('saveState').textContent='Modifications non enregistrées';};
form.onsubmit=event=>{event.preventDefault();run(async()=>{const data=Object.fromEntries(new FormData(form));data.position=Number(data.position);for(const key of ['start_year','end_year'])data[key]=data[key]===''?null:Number(data[key]);data.visible=form.elements.visible.checked;if(current)data.revision=current.revision;const saved=await api('/api/admin/timeline'+(current?'/'+current.id:''),current?'PUT':'POST',data);edit(saved);await load();notice(saved.visible?'Événement révélé dans la frise.':'Événement enregistré en privé.');});};
$('search').oninput=()=>{page=1;clearTimeout(timer);controller?.abort();timer=setTimeout(()=>load().catch(e=>notice(e.message)),250);};$('kindFilter').onchange=()=>{page=1;load().catch(e=>notice(e.message));};$('prevPage').onclick=()=>{page--;load().catch(e=>notice(e.message));};$('nextPage').onclick=()=>{page++;load().catch(e=>notice(e.message));};
$('importFile').onchange=async()=>{importData=null;$('importEvents').disabled=true;$('importPreview').replaceChildren();const file=$('importFile').files[0];if(!file)return;try{if(file.size>2*1024*1024)throw Error('Le fichier dépasse 2 Mo.');const data=JSON.parse(await file.text());if(data.version!==1||!Array.isArray(data.events)||!data.events.length||data.events.length>200||data.events.some(e=>!e||typeof e.title!=='string'||typeof e.source_key!=='string'))throw Error('Fichier d’import invalide.');importData=data;for(const e of data.events)$('importPreview').append(make('li',e.title));$('importInfo').textContent=data.events.length+' éléments prêts à être importés en privé.';$('importEvents').disabled=false;}catch(error){$('importInfo').textContent=error.message;}};
$('importEvents').onclick=()=>{if(importData&&canLeave())run(async()=>{const result=await api('/api/admin/timeline/import','POST',importData);importData=null;$('importEvents').disabled=true;$('importFile').value='';$('importPreview').replaceChildren();$('importInfo').textContent=result.added+' éléments importés en privé ; '+result.skipped+' déjà présents.';page=1;$('search').value='';$('kindFilter').value='all';await load();});};
$('deleteEvent').onclick=()=>{$('deleteWarning').textContent='Supprimer définitivement « '+current.title+' » ?';$('confirmTitle').value='';$('deleteDialog').showModal();};$('cancelDelete').onclick=()=>$('deleteDialog').close();$('confirmTitle').oninput=()=>$('confirmTitle').setCustomValidity('');
$('deleteForm').onsubmit=event=>{event.preventDefault();if($('confirmTitle').value!==current.title){$('confirmTitle').setCustomValidity('Retapez exactement le titre.');$('confirmTitle').reportValidity();return;}$('deleteDialog').close();run(async()=>{await api('/api/admin/timeline/'+current.id,'DELETE',{revision:current.revision,confirmTitle:$('confirmTitle').value});dirty=false;current=null;form.hidden=true;$('welcome').hidden=false;await load();notice('Événement supprimé.');});};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
(async()=>{try{const session=await api('/api/admin/session');csrf=session.csrf;await load();$('timelineWorkspace').hidden=false;notice('Votre chronologie reste privée jusqu’à ce que vous révéliez ses événements.');}catch(error){notice(error.message+' ');const link=make('a','Se connecter');link.href='/account/';$('notice').append(link);}})();
